language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq uuid-dev valac libjansson-dev re2c
 - git clone --depth=50 --branch=release-2-11-3 https://bitbucket.org/tildeslash/libzdb.git deps/libzdb
 - git clone --depth=50 --branch=master git://github.com/haiwen/libsearpc.git deps/libsearpc
 - cd deps/libzdb && ./bootstrap && ./configure --without-postgresql --without-mysql && make -j8 && sudo make install && cd -
 - cd deps/libsearpc && ./autogen.sh && ./configure
 - cd demo && python ../lib/searpc-codegen.py rpc_table.py && cd -
 - cd tests && python ../lib/searpc-codegen.py rpc_table.py && cd -
 - make -j8 && sudo make install && cd ../..
 - ./autogen.sh
script:
 - cd lib && python `which searpc-codegen.py` ./rpc_table.py && cd -
 - ./configure --enable-server --enable-client
 - make -j8
 - make check
notifications:
    email: false
