language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo add-apt-repository -y ppa:ondrej/seafile
 - sudo apt-get update -qq
 - sudo apt-get install -qq uuid-dev valac
 - sudo apt-get install -y libzdb-dev libsearpc-dev python-searpc
 - ./autogen.sh
script:
 - searpc-codegen ./lib/rpc_table.py
 - ./configure --enable-server --enable-client
 - make -j8
 - make check
notifications:
    email: false
